import * as THREE from "three";
import { RoundedBoxGeometry } from "three/addons/geometries/RoundedBoxGeometry.js";

/* ============================================================================
 * kCube — a 3D dice-rolling puzzle.
 *
 * Roll cubes around a 5×5 board until every cube shows the same colour on top
 * AND they form one connected (N/S/E/W) block, within a limited move budget.
 * Levels are generated by scrambling a solved board with random reverse-rolls,
 * which guarantees solvability; the exact reverse is stored so it can be played
 * back as a "show solution". Best scores are persisted in localStorage so any
 * level can be replayed to beat your record.
 * ========================================================================== */

/* --- Constants -------------------------------------------------------------- */

const BOARD = 5; // 5×5 grid
const S = 1.0; // cell spacing == cube size (so a roll lands exactly one cell over)
const HALF = S / 2;
const ROLL_MS = 170; // duration of a roll animation
const STORE_KEY = "kcube.v1"; // localStorage key for persisted scores

// Six distinct face colours. Index doubles as the "face id".
const COLORS = [
  { name: "white", hex: 0xf2f3f5 },
  { name: "yellow", hex: 0xffd23f },
  { name: "red", hex: 0xe5484d },
  { name: "orange", hex: 0xff7a1a },
  { name: "blue", hex: 0x3aa0ff },
  { name: "green", hex: 0x3ecf6b },
];

// Fixed mapping from a cube's LOCAL face axis -> colour id. Every cube shares
// this mapping; only orientation differs. The "solved" colour (identity
// orientation, +Y up) is white.
const FACE_AXES = [
  { v: new THREE.Vector3(1, 0, 0), color: 2 }, // +X red
  { v: new THREE.Vector3(-1, 0, 0), color: 3 }, // -X orange
  { v: new THREE.Vector3(0, 1, 0), color: 0 }, // +Y white  (solved = up)
  { v: new THREE.Vector3(0, -1, 0), color: 1 }, // -Y yellow
  { v: new THREE.Vector3(0, 0, 1), color: 4 }, // +Z blue
  { v: new THREE.Vector3(0, 0, -1), color: 5 }, // -Z green
];
const SOLVED_COLOR = 0; // white ends up on top of a freshly-solved board

// Arrow-key directions. dr/dc are board deltas; the pivot + rotation describe
// the physical tip-over used both for the animation and the resulting
// orientation. edgeOffset is added to the cube CENTRE to find the contact edge.
const DIRS = {
  ArrowRight: {
    dr: 0, dc: 1,
    axis: new THREE.Vector3(0, 0, 1), angle: -Math.PI / 2,
    edgeOffset: new THREE.Vector3(HALF, -HALF, 0),
  },
  ArrowLeft: {
    dr: 0, dc: -1,
    axis: new THREE.Vector3(0, 0, 1), angle: Math.PI / 2,
    edgeOffset: new THREE.Vector3(-HALF, -HALF, 0),
  },
  ArrowUp: {
    dr: -1, dc: 0,
    axis: new THREE.Vector3(1, 0, 0), angle: -Math.PI / 2,
    edgeOffset: new THREE.Vector3(0, -HALF, -HALF),
  },
  ArrowDown: {
    dr: 1, dc: 0,
    axis: new THREE.Vector3(1, 0, 0), angle: Math.PI / 2,
    edgeOffset: new THREE.Vector3(0, -HALF, HALF),
  },
};

// Reverse of each roll direction (used to undo a scramble for "show solution").
const OPPOSITE = {
  ArrowRight: "ArrowLeft", ArrowLeft: "ArrowRight",
  ArrowUp: "ArrowDown", ArrowDown: "ArrowUp",
};

// 4-neighbourhood for connectivity / adjacency tests.
const NEI = [[1, 0], [-1, 0], [0, 1], [0, -1]];

/* --- Helpers ---------------------------------------------------------------- */

const randInt = (n) => Math.floor(Math.random() * n);
const cellX = (col) => (col - (BOARD - 1) / 2) * S;
const cellZ = (row) => (row - (BOARD - 1) / 2) * S;
const inBounds = (r, c) => r >= 0 && r < BOARD && c >= 0 && c < BOARD;

// Build a canvas texture: a coloured rounded square on a dark background, so
// faces read clearly and adjacent cubes still show a seam between them.
function faceTexture(hex) {
  const size = 128;
  const cv = document.createElement("canvas");
  cv.width = cv.height = size;
  const ctx = cv.getContext("2d");
  ctx.fillStyle = "#0c0e16";
  ctx.fillRect(0, 0, size, size);
  const pad = 12, r = 22, w = size - pad * 2;
  const col = "#" + hex.toString(16).padStart(6, "0");
  ctx.fillStyle = col;
  ctx.beginPath();
  ctx.roundRect(pad, pad, w, w, r);
  ctx.fill();
  // subtle top sheen
  const grad = ctx.createLinearGradient(0, pad, 0, pad + w);
  grad.addColorStop(0, "rgba(255,255,255,0.22)");
  grad.addColorStop(0.5, "rgba(255,255,255,0)");
  ctx.fillStyle = grad;
  ctx.beginPath();
  ctx.roundRect(pad, pad, w, w, r);
  ctx.fill();
  const tex = new THREE.CanvasTexture(cv);
  tex.anisotropy = 4;
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}

// BoxGeometry material order is: +X, -X, +Y, -Y, +Z, -Z — matching FACE_AXES.
const FACE_MATERIALS = FACE_AXES.map(
  (f) => new THREE.MeshStandardMaterial({
    map: faceTexture(COLORS[f.color].hex),
    roughness: 0.55,
    metalness: 0.05,
  })
);

// Which colour faces up for a given orientation quaternion.
const _tmp = new THREE.Vector3();
function topColor(quat) {
  let best = -Infinity, color = 0;
  for (const f of FACE_AXES) {
    _tmp.copy(f.v).applyQuaternion(quat);
    if (_tmp.y > best) { best = _tmp.y; color = f.color; }
  }
  return color;
}

/* A lightly bevelled cube. RoundedBoxGeometry is single-material, so we rebuild
 * the per-face material groups (BoxGeometry order: +X,-X,+Y,-Y,+Z,-Z) by
 * classifying each triangle to the face its centroid points toward. The bevel
 * is slight, so colouring the thin rounded edges by nearest face reads cleanly. */
function bevelledCubeGeometry(size, radius, segments) {
  // RoundedBoxGeometry is non-indexed: every 3 consecutive vertices form one
  // triangle. Classify each triangle's centroid to a face and emit a run of
  // material groups so the 6 face textures map onto the bevelled box.
  const geo = new RoundedBoxGeometry(size, size, size, segments, radius);
  const pos = geo.attributes.position;
  const faceOf = (x, y, z) => {
    const ax = Math.abs(x), ay = Math.abs(y), az = Math.abs(z);
    if (ax >= ay && ax >= az) return x >= 0 ? 0 : 1;
    if (ay >= az) return y >= 0 ? 2 : 3;
    return z >= 0 ? 4 : 5;
  };
  geo.clearGroups();
  const tris = pos.count / 3;
  let runStart = 0, runMat = -1;
  for (let t = 0; t < tris; t++) {
    const i = t * 3;
    const x = (pos.getX(i) + pos.getX(i + 1) + pos.getX(i + 2)) / 3;
    const y = (pos.getY(i) + pos.getY(i + 1) + pos.getY(i + 2)) / 3;
    const z = (pos.getZ(i) + pos.getZ(i + 1) + pos.getZ(i + 2)) / 3;
    const m = faceOf(x, y, z);
    if (m !== runMat) {
      if (runMat !== -1) geo.addGroup(runStart * 3, (t - runStart) * 3, runMat);
      runStart = t; runMat = m;
    }
  }
  geo.addGroup(runStart * 3, (tris - runStart) * 3, runMat);
  return geo;
}

/* --- Persisted scores ------------------------------------------------------- */

function loadStore() {
  try { return JSON.parse(localStorage.getItem(STORE_KEY)) || {}; }
  catch { return {}; }
}
function saveStore(s) {
  try { localStorage.setItem(STORE_KEY, JSON.stringify(s)); } catch { /* ignore */ }
}
function bestFor(level) {
  const b = loadStore().best;
  return b && b[level] !== undefined ? b[level] : null;
}
function maxLevel() {
  return loadStore().maxLevel || 0;
}
// Record a clear: keep the fewest moves ever used to solve this level index.
function recordScore(level, movesUsed) {
  const s = loadStore();
  s.best = s.best || {};
  s.cleared = s.cleared || {};
  const prev = s.best[level];
  const isRecord = prev === undefined || movesUsed < prev;
  if (isRecord) s.best[level] = movesUsed;
  s.cleared[level] = (s.cleared[level] || 0) + 1;
  s.maxLevel = Math.max(s.maxLevel || 0, level);
  saveStore(s);
  return { isRecord, best: s.best[level], prev };
}

/* --- Three.js scene --------------------------------------------------------- */

const canvas = document.getElementById("scene");
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

const scene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(46, 1, 0.1, 100);
// Orbit the camera around the vertical axis with Q/E. We keep a fixed radius and
// height and only vary the yaw angle, easing toward a target for a smooth turn.
const CAM_R = 6.6; // horizontal distance from board centre
const CAM_H = 7.4; // camera height
let camYaw = 0, camYawTarget = 0;
function applyCamera() {
  camera.position.set(Math.sin(camYaw) * CAM_R, CAM_H, Math.cos(camYaw) * CAM_R);
  camera.lookAt(0, 0, 0);
}
applyCamera();

// Lights
scene.add(new THREE.AmbientLight(0xffffff, 0.55));
const key = new THREE.DirectionalLight(0xffffff, 1.15);
key.position.set(4, 9, 5);
key.castShadow = true;
key.shadow.mapSize.set(2048, 2048);
key.shadow.camera.near = 1;
key.shadow.camera.far = 30;
key.shadow.camera.left = -6;
key.shadow.camera.right = 6;
key.shadow.camera.top = 6;
key.shadow.camera.bottom = -6;
scene.add(key);
const fill = new THREE.DirectionalLight(0x88aaff, 0.35);
fill.position.set(-5, 4, -4);
scene.add(fill);

// Board group (tiles + base). Tinted toward the target colour as a hint.
const boardGroup = new THREE.Group();
scene.add(boardGroup);

const baseGeo = new THREE.BoxGeometry(BOARD * S + 0.5, 0.4, BOARD * S + 0.5);
const baseMat = new THREE.MeshStandardMaterial({ color: 0x161a26, roughness: 0.9 });
const base = new THREE.Mesh(baseGeo, baseMat);
base.position.y = -0.2 - 0.001;
base.receiveShadow = true;
boardGroup.add(base);

const tileGeo = new THREE.BoxGeometry(S * 0.94, 0.12, S * 0.94);
const tileMats = [];
for (let r = 0; r < BOARD; r++) {
  for (let c = 0; c < BOARD; c++) {
    const mat = new THREE.MeshStandardMaterial({
      color: (r + c) % 2 ? 0x222838 : 0x2a3145,
      roughness: 0.85,
    });
    const tile = new THREE.Mesh(tileGeo, mat);
    tile.position.set(cellX(c), -0.06, cellZ(r));
    tile.receiveShadow = true;
    boardGroup.add(tile);
    tileMats.push(mat);
  }
}

// Floating down-pointing arrow that marks the selected cube.
const cursor = new THREE.Group();
{
  const mat = new THREE.MeshStandardMaterial({
    color: 0x6ee7ff, emissive: 0x2a6f88, roughness: 0.3, metalness: 0.2,
  });
  const head = new THREE.Mesh(new THREE.ConeGeometry(0.17, 0.3, 22), mat);
  head.rotation.x = Math.PI; // tip points down toward the cube
  const shaft = new THREE.Mesh(new THREE.CylinderGeometry(0.06, 0.06, 0.26, 16), mat);
  shaft.position.y = 0.27;
  cursor.add(head, shaft);
}
scene.add(cursor);

/* --- Cube objects ----------------------------------------------------------- */

const cubeGeo = bevelledCubeGeometry(S, 0.08, 3);

class Cube {
  constructor(row, col) {
    this.mesh = new THREE.Mesh(cubeGeo, FACE_MATERIALS);
    this.mesh.castShadow = true;
    this.mesh.receiveShadow = true;
    scene.add(this.mesh);
    this.setCell(row, col);
    this.mesh.quaternion.identity(); // solved
    this.syncMesh();
  }
  setCell(row, col) {
    this.row = row;
    this.col = col;
  }
  syncMesh() {
    this.mesh.position.set(cellX(this.col), HALF, cellZ(this.row));
  }
  get topColor() {
    return topColor(this.mesh.quaternion);
  }
  dispose() {
    scene.remove(this.mesh);
  }
}

/* --- Game state ------------------------------------------------------------- */

const game = {
  level: 1,
  menuLevel: 1, // level chosen on the menu (for replays)
  bonus: 0, // carried-over moves earned by clearing levels
  cubes: [],
  selected: null, // index into cubes
  moves: 0, // remaining move budget
  movesUsed: 0, // rolls spent this level (the score)
  targetColor: SOLVED_COLOR,
  state: "menu", // menu | playing | solving | won | lost
  anim: null, // active roll animation
  solution: [], // recorded solving moves: [{cube, key}]
  initial: [], // snapshot of the scrambled start, for replaying the solution
  solving: false, // true while auto-playing the solution
  solveQueue: [],
};

const el = {
  level: document.getElementById("level"),
  moves: document.getElementById("moves"),
  cubes: document.getElementById("cubes"),
  best: document.getElementById("best"),
  overlay: document.getElementById("overlay"),
  title: document.getElementById("overlay-title"),
  body: document.getElementById("overlay-body"),
  btn: document.getElementById("overlay-btn"),
  solveBtn: document.getElementById("solveBtn"),
  menuBtn: document.getElementById("menuBtn"),
};

function cubeAt(row, col) {
  return game.cubes.find((c) => c.row === row && c.col === col) || null;
}

function occupied(row, col) {
  return game.cubes.some((c) => c.row === row && c.col === col);
}

// Are the given [row,col] cells a single 4-connected (N/S/E/W) block?
function cellsConnected(cells) {
  if (cells.length <= 1) return true;
  const set = new Set(cells.map(([r, c]) => r * BOARD + c));
  const seen = new Set();
  const stack = [cells[0]];
  seen.add(cells[0][0] * BOARD + cells[0][1]);
  while (stack.length) {
    const [r, c] = stack.pop();
    for (const [dr, dc] of NEI) {
      const nr = r + dr, nc = c + dc, k = nr * BOARD + nc;
      if (set.has(k) && !seen.has(k)) { seen.add(k); stack.push([nr, nc]); }
    }
  }
  return seen.size === set.size;
}

function isContiguous() {
  return cellsConnected(game.cubes.map((c) => [c.row, c.col]));
}

// Grow a random 4-connected blob of n cells from the board centre. The solved
// target must itself be contiguous, since the win condition now requires it.
function connectedCells(n) {
  const mid = Math.floor(BOARD / 2);
  const inSet = new Set([mid * BOARD + mid]);
  const chosen = [[mid, mid]];
  const frontier = [];
  const pushNei = (r, c) => {
    for (const [dr, dc] of NEI) {
      const nr = r + dr, nc = c + dc;
      if (inBounds(nr, nc) && !inSet.has(nr * BOARD + nc)) frontier.push([nr, nc]);
    }
  };
  pushNei(mid, mid);
  while (chosen.length < n && frontier.length) {
    const [r, c] = frontier.splice(randInt(frontier.length), 1)[0];
    const k = r * BOARD + c;
    if (inSet.has(k)) continue;
    inSet.add(k);
    chosen.push([r, c]);
    pushNei(r, c);
  }
  return chosen;
}

/* --- Level generation ------------------------------------------------------
 * Start from a solved board (all cubes identity-oriented => white up) placed in
 * a single contiguous block, then apply N random reverse-rolls. Because every
 * scramble step is a legal roll, reversing the sequence solves the board AND
 * returns the cubes to their contiguous start => guaranteed solvable. The
 * recorded reverse sequence powers "show solution".
 * ------------------------------------------------------------------------- */

function levelParams(level) {
  const numCubes = Math.min(25, 2 + level);
  const scramble = 3 + Math.floor(level * 1.6);
  return { numCubes, scramble };
}

function scrambleRoll(cube) {
  // Pick a random direction whose target cell is on-board and empty, then roll.
  // Returns the direction key used (so the scramble can be replayed), or null.
  const keys = Object.keys(DIRS).sort(() => Math.random() - 0.5);
  for (const k of keys) {
    const d = DIRS[k];
    const nr = cube.row + d.dr, nc = cube.col + d.dc;
    if (!inBounds(nr, nc) || occupied(nr, nc)) continue;
    applyRollLogic(cube, d, nr, nc);
    return k;
  }
  return null;
}

// Apply a roll to logical + mesh state instantly (no animation).
function applyRollLogic(cube, dir, nr, nc) {
  const q = new THREE.Quaternion().setFromAxisAngle(dir.axis, dir.angle);
  cube.mesh.quaternion.premultiply(q);
  cube.setCell(nr, nc);
  cube.syncMesh();
}

function buildLevel(level) {
  // clear old cubes
  for (const c of game.cubes) c.dispose();
  game.cubes = [];

  const { numCubes, scramble } = levelParams(level);

  // place cubes as a single contiguous block, solved orientation
  for (const [r, c] of connectedCells(numCubes)) game.cubes.push(new Cube(r, c));

  // scramble with random reverse-rolls, recording each so the exact reverse can
  // be replayed as the solution
  const scrambleMoves = [];
  let applied = 0, guard = 0;
  while (applied < scramble && guard < scramble * 20) {
    guard++;
    const cube = game.cubes[randInt(game.cubes.length)];
    const k = scrambleRoll(cube);
    if (k) { applied++; scrambleMoves.push({ cube, key: k }); }
  }

  game.targetColor = SOLVED_COLOR;

  // If by luck the scramble produced an already-solved board, nudge once more.
  if (isSolved()) {
    const cube = game.cubes[randInt(game.cubes.length)];
    const k = scrambleRoll(cube);
    if (k) scrambleMoves.push({ cube, key: k });
  }

  // Solution = scramble reversed, each roll undone in the opposite direction.
  // This walks the board back through the same states to the contiguous,
  // uniform start, so it satisfies the win condition.
  game.solution = scrambleMoves
    .slice().reverse()
    .map(({ cube, key }) => ({ cube, key: OPPOSITE[key] }));

  // Snapshot the scrambled start so "show solution" can replay from here.
  game.initial = game.cubes.map((c) => ({
    cube: c, row: c.row, col: c.col, quat: c.mesh.quaternion.clone(),
  }));

  // Move budget. Par is well above the raw scramble count: the cursor can only
  // hop between cubes that are N/S/E/W-adjacent, so cubes scattered into disjoint
  // clusters must be herded back into one block — far more moves than merely
  // undoing the scramble.
  game.moves = scramble + game.cubes.length * 3 + 4 + game.bonus;
  game.movesUsed = 0;
  game.selected = 0;
  game.solving = false;
  game.solveQueue = [];

  tintBoard(game.targetColor);
  updateCursor(true);
  updateHud();
}

/* --- Win / lose ------------------------------------------------------------- */

function isUniform() {
  if (game.cubes.length === 0) return false;
  const t = game.cubes[0].topColor;
  return game.cubes.every((c) => c.topColor === t);
}

// Solved = same colour up on every cube AND a single connected block.
function isSolved() {
  return isUniform() && isContiguous();
}

function tintBoard(colorId) {
  const c = new THREE.Color(COLORS[colorId].hex);
  for (const m of tileMats) {
    m.emissive = c;
    m.emissiveIntensity = 0.12;
  }
  baseMat.emissive = c;
  baseMat.emissiveIntensity = 0.05;
}

/* --- Input / rolling -------------------------------------------------------- */

function selectCube(idx) {
  game.selected = idx;
  updateCursor(true);
}

function tryMove(key) {
  if (game.state !== "playing" || game.anim) return;
  const dir = DIRS[key];
  if (!dir) return;
  const cube = game.cubes[game.selected];
  const nr = cube.row + dir.dr, nc = cube.col + dir.dc;
  if (!inBounds(nr, nc)) return; // edge: nothing happens

  const other = cubeAt(nr, nc);
  if (other) {
    // re-select neighbour — free, no move spent
    selectCube(game.cubes.indexOf(other));
    return;
  }

  if (game.moves <= 0) return;
  startRoll(cube, dir, nr, nc, true);
}

// cost=false rolls are free (used when auto-playing the solution).
function startRoll(cube, dir, nr, nc, cost) {
  const center = cube.mesh.position.clone();
  const pivot = center.clone().add(dir.edgeOffset);
  game.anim = {
    cube, dir, nr, nc, pivot,
    startPos: center.clone().sub(pivot), // position relative to pivot
    startQuat: cube.mesh.quaternion.clone(),
    t: 0,
  };
  if (cost) {
    game.moves -= 1;
    game.movesUsed += 1;
  }
  updateHud();
}

function stepRoll(dt) {
  const a = game.anim;
  a.t = Math.min(1, a.t + dt / ROLL_MS);
  // ease-in-out for a satisfying tip
  const e = a.t < 0.5 ? 2 * a.t * a.t : 1 - Math.pow(-2 * a.t + 2, 2) / 2;
  const angle = a.dir.angle * e;
  const q = new THREE.Quaternion().setFromAxisAngle(a.dir.axis, angle);
  a.cube.mesh.position.copy(a.startPos).applyQuaternion(q).add(a.pivot);
  a.cube.mesh.quaternion.copy(a.startQuat).premultiply(q);

  if (a.t >= 1) {
    // snap to final logical state
    const final = new THREE.Quaternion().setFromAxisAngle(a.dir.axis, a.dir.angle);
    a.cube.mesh.quaternion.copy(a.startQuat).premultiply(final);
    a.cube.setCell(a.nr, a.nc);
    a.cube.syncMesh();
    game.anim = null;
    updateCursor(false);
    if (game.solving) solutionStep();
    else afterMove();
  } else {
    updateCursor(false);
  }
}

function afterMove() {
  if (isSolved()) {
    game.state = "won";
    game.bonus += 1; // clearing a level grants +1 carried move
    const { isRecord, best, prev } = recordScore(game.level, game.movesUsed);
    const scoreLine = isRecord
      ? (prev === undefined
          ? `Solved in <b>${game.movesUsed}</b> moves.`
          : `Solved in <b>${game.movesUsed}</b> moves — <b>new best!</b> (was ${prev})`)
      : `Solved in <b>${game.movesUsed}</b> moves (best ${best}).`;
    showOverlay(
      "Solved!",
      `${scoreLine}<br>Level ${game.level} cleared. <b>+1</b> bonus move banked (carried: ${game.bonus}).`,
      "Next level"
    );
    updateHud();
  } else if (game.moves <= 0) {
    game.state = "lost";
    showOverlay(
      "Out of moves",
      "Not quite — every cube the same colour in one connected block. Press <b>S</b> to see a solution, or retry.",
      "Retry"
    );
  }
}

/* --- Show solution ---------------------------------------------------------- */

function restoreInitial() {
  for (const s of game.initial) {
    s.cube.setCell(s.row, s.col);
    s.cube.mesh.quaternion.copy(s.quat);
    s.cube.syncMesh();
  }
}

function showSolution() {
  if (game.anim || game.solving) return;
  if (game.state !== "playing" && game.state !== "lost") return;
  if (game.solution.length === 0) return;
  hideOverlay();
  restoreInitial(); // rewind to the scrambled start
  game.solving = true;
  game.state = "solving";
  game.solveQueue = game.solution.slice();
  game.selected = 0;
  updateCursor(true);
  updateHud();
  solutionStep();
}

function solutionStep() {
  if (game.solveQueue.length === 0) {
    game.solving = false;
    game.state = "lost"; // not a legitimate clear — offer a retry
    showOverlay(
      "Solution",
      "That's one way: every cube the same colour in one connected block. Press <b>Retry</b> for a fresh scramble.",
      "Retry"
    );
    return;
  }
  const { cube, key } = game.solveQueue.shift();
  game.selected = game.cubes.indexOf(cube);
  updateCursor(true);
  const dir = DIRS[key];
  startRoll(cube, dir, cube.row + dir.dr, cube.col + dir.dc, false);
}

/* --- Presentation: cursor + HUD -------------------------------------------- */

function updateCursor(snap) {
  const cube = game.cubes[game.selected];
  if (!cube) return;
  const tx = cube.mesh.position.x;
  const tz = cube.mesh.position.z;
  if (snap) {
    cursor.position.set(tx, S + 0.55, tz);
  } else {
    cursor.position.x += (tx - cursor.position.x) * 0.4;
    cursor.position.z += (tz - cursor.position.z) * 0.4;
  }
}

function updateHud() {
  el.level.textContent = game.level;
  el.moves.textContent = Math.max(0, game.moves);
  el.cubes.textContent = game.cubes.length;
  const b = bestFor(game.level);
  el.best.textContent = b === null ? "–" : b;
}

function showOverlay(title, body, btn) {
  el.title.textContent = title;
  el.body.innerHTML = body;
  el.btn.textContent = btn;
  el.overlay.classList.remove("hidden");
}

function hideOverlay() {
  el.overlay.classList.add("hidden");
}

// The menu doubles as a level picker: ◀ ▶ choose a level (any you've reached,
// plus the next new one) and Play/Replay it to beat your best score.
function showMenu() {
  game.state = "menu";
  const max = maxLevel();
  game.menuLevel = Math.min(Math.max(1, game.menuLevel), max + 1);
  const lvl = game.menuLevel;
  const b = bestFor(lvl);
  el.title.textContent = "kCube";
  el.body.innerHTML =
    "Roll cubes so they all show the <b>same colour</b> on top <b>and</b> form one " +
    "connected block.<br><br>" +
    `<b>◀ ▶</b> choose level &nbsp;·&nbsp; Level <b>${lvl}</b>` +
    (b === null
      ? ` &nbsp;·&nbsp; <span style="opacity:.6">unplayed</span>`
      : ` &nbsp;·&nbsp; best <b>${b}</b> moves`) +
    (max ? `<br><span style="opacity:.6">reached level ${max}</span>` : "");
  el.btn.textContent = lvl <= max ? "Replay" : "Play";
  el.overlay.classList.remove("hidden");
}

/* --- Flow control ----------------------------------------------------------- */

function startGame() {
  game.level = game.menuLevel || 1;
  game.bonus = 0; // a chosen-level run starts from a clean bonus
  hideOverlay();
  buildLevel(game.level);
  game.state = "playing";
}

function nextLevel() {
  game.level += 1;
  game.menuLevel = game.level;
  hideOverlay();
  buildLevel(game.level);
  game.state = "playing";
}

function retryLevel() {
  hideOverlay();
  buildLevel(game.level); // fresh scramble of the same level index
  game.state = "playing";
}

function overlayAction() {
  if (game.state === "menu") startGame();
  else if (game.state === "won") nextLevel();
  else retryLevel(); // lost
}

el.btn.addEventListener("click", overlayAction);
el.solveBtn.addEventListener("click", () => { showSolution(); el.solveBtn.blur(); });
el.menuBtn.addEventListener("click", () => { if (!game.solving) showMenu(); el.menuBtn.blur(); });

window.addEventListener("keydown", (e) => {
  // Q/E orbit the view around the vertical axis, in any state.
  if (e.key === "q" || e.key === "Q") { camYawTarget += Math.PI / 8; return; }
  if (e.key === "e" || e.key === "E") { camYawTarget -= Math.PI / 8; return; }

  if (DIRS[e.key]) {
    e.preventDefault();
    if (game.state === "playing") {
      tryMove(e.key);
    } else if (game.state === "menu") {
      // arrows pick the level to play/replay
      const max = maxLevel() + 1;
      if (e.key === "ArrowRight") game.menuLevel = Math.min(max, game.menuLevel + 1);
      else if (e.key === "ArrowLeft") game.menuLevel = Math.max(1, game.menuLevel - 1);
      else return;
      showMenu();
    }
    return;
  }

  if (e.key === "Enter" || e.key === " ") {
    if (!el.overlay.classList.contains("hidden")) {
      e.preventDefault();
      overlayAction();
    }
  } else if (e.key === "r" || e.key === "R") {
    if (game.state === "playing" || game.state === "lost") retryLevel();
  } else if (e.key === "s" || e.key === "S") {
    showSolution();
  } else if (e.key === "m" || e.key === "M") {
    if (!game.solving) showMenu();
  }
});

/* --- Render loop ------------------------------------------------------------ */

function resize() {
  const w = window.innerWidth, h = window.innerHeight;
  renderer.setSize(w, h, false);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
}
window.addEventListener("resize", resize);
resize();

let last = performance.now();
function loop(now) {
  const dt = Math.min(now - last, 50);
  last = now;

  if (game.anim) stepRoll(dt);

  // ease the camera toward its target yaw
  if (Math.abs(camYawTarget - camYaw) > 1e-4) {
    camYaw += (camYawTarget - camYaw) * 0.15;
    applyCamera();
  }

  // animate cursor: spin + bob
  cursor.rotation.y += dt * 0.003;
  cursor.position.y = S + 0.55 + Math.sin(now * 0.004) * 0.07;

  renderer.render(scene, camera);
  requestAnimationFrame(loop);
}

// Boot — open on the menu/level picker, defaulting to the next unplayed level.
game.menuLevel = maxLevel() + 1;
showMenu();
requestAnimationFrame(loop);
