import * as THREE from "three";

/* ============================================================================
 * kCube — a 3D dice-rolling puzzle.
 *
 * Roll cubes around a 5×5 board until every cube shows the same colour on top,
 * within a limited move budget. Levels are generated by scrambling a solved
 * board with random reverse-rolls, which guarantees solvability.
 * ========================================================================== */

/* --- Constants -------------------------------------------------------------- */

const BOARD = 5; // 5×5 grid
const S = 1.0; // cell spacing == cube size (so a roll lands exactly one cell over)
const HALF = S / 2;
const ROLL_MS = 170; // duration of a roll animation

// Six distinct face colours. Index doubles as the "face id".
const COLORS = [
  { name: "white", hex: 0xf2f3f5 },
  { name: "yellow", hex: 0xffd23f },
  { name: "red", hex: 0xe5484d },
  { name: "orange", hex: 0xff7a1a },
  { name: "blue", hex: 0x3aa0ff },
  { name: "green", hex: 0x3ecf6b },
];

// Fixed mapping from a cube's LOCAL face axis -> colour id. Every cube shares
// this mapping; only orientation differs. The "solved" colour (identity
// orientation, +Y up) is white.
const FACE_AXES = [
  { v: new THREE.Vector3(1, 0, 0), color: 2 }, // +X red
  { v: new THREE.Vector3(-1, 0, 0), color: 3 }, // -X orange
  { v: new THREE.Vector3(0, 1, 0), color: 0 }, // +Y white  (solved = up)
  { v: new THREE.Vector3(0, -1, 0), color: 1 }, // -Y yellow
  { v: new THREE.Vector3(0, 0, 1), color: 4 }, // +Z blue
  { v: new THREE.Vector3(0, 0, -1), color: 5 }, // -Z green
];
const SOLVED_COLOR = 0; // white ends up on top of a freshly-solved board

// Arrow-key directions. dr/dc are board deltas; the pivot + rotation describe
// the physical tip-over used both for the animation and the resulting
// orientation. edgeOffset is added to the cube CENTRE to find the contact edge.
const DIRS = {
  ArrowRight: {
    dr: 0, dc: 1,
    axis: new THREE.Vector3(0, 0, 1), angle: -Math.PI / 2,
    edgeOffset: new THREE.Vector3(HALF, -HALF, 0),
  },
  ArrowLeft: {
    dr: 0, dc: -1,
    axis: new THREE.Vector3(0, 0, 1), angle: Math.PI / 2,
    edgeOffset: new THREE.Vector3(-HALF, -HALF, 0),
  },
  ArrowUp: {
    dr: -1, dc: 0,
    axis: new THREE.Vector3(1, 0, 0), angle: -Math.PI / 2,
    edgeOffset: new THREE.Vector3(0, -HALF, -HALF),
  },
  ArrowDown: {
    dr: 1, dc: 0,
    axis: new THREE.Vector3(1, 0, 0), angle: Math.PI / 2,
    edgeOffset: new THREE.Vector3(0, -HALF, HALF),
  },
};

/* --- Helpers ---------------------------------------------------------------- */

const randInt = (n) => Math.floor(Math.random() * n);
const cellX = (col) => (col - (BOARD - 1) / 2) * S;
const cellZ = (row) => (row - (BOARD - 1) / 2) * S;
const inBounds = (r, c) => r >= 0 && r < BOARD && c >= 0 && c < BOARD;

// Build a canvas texture: a coloured rounded square on a dark background, so
// faces read clearly and adjacent cubes still show a seam between them.
function faceTexture(hex) {
  const size = 128;
  const cv = document.createElement("canvas");
  cv.width = cv.height = size;
  const ctx = cv.getContext("2d");
  ctx.fillStyle = "#0c0e16";
  ctx.fillRect(0, 0, size, size);
  const pad = 12, r = 22, w = size - pad * 2;
  const col = "#" + hex.toString(16).padStart(6, "0");
  ctx.fillStyle = col;
  ctx.beginPath();
  ctx.roundRect(pad, pad, w, w, r);
  ctx.fill();
  // subtle top sheen
  const grad = ctx.createLinearGradient(0, pad, 0, pad + w);
  grad.addColorStop(0, "rgba(255,255,255,0.22)");
  grad.addColorStop(0.5, "rgba(255,255,255,0)");
  ctx.fillStyle = grad;
  ctx.beginPath();
  ctx.roundRect(pad, pad, w, w, r);
  ctx.fill();
  const tex = new THREE.CanvasTexture(cv);
  tex.anisotropy = 4;
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}

// BoxGeometry material order is: +X, -X, +Y, -Y, +Z, -Z — matching FACE_AXES.
const FACE_MATERIALS = FACE_AXES.map(
  (f) => new THREE.MeshStandardMaterial({
    map: faceTexture(COLORS[f.color].hex),
    roughness: 0.55,
    metalness: 0.05,
  })
);

// Which colour faces up for a given orientation quaternion.
const _tmp = new THREE.Vector3();
function topColor(quat) {
  let best = -Infinity, color = 0;
  for (const f of FACE_AXES) {
    _tmp.copy(f.v).applyQuaternion(quat);
    if (_tmp.y > best) { best = _tmp.y; color = f.color; }
  }
  return color;
}

/* --- Three.js scene --------------------------------------------------------- */

const canvas = document.getElementById("scene");
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

const scene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(46, 1, 0.1, 100);
camera.position.set(0, 7.4, 6.6);
camera.lookAt(0, 0, 0);

// Lights
scene.add(new THREE.AmbientLight(0xffffff, 0.55));
const key = new THREE.DirectionalLight(0xffffff, 1.15);
key.position.set(4, 9, 5);
key.castShadow = true;
key.shadow.mapSize.set(2048, 2048);
key.shadow.camera.near = 1;
key.shadow.camera.far = 30;
key.shadow.camera.left = -6;
key.shadow.camera.right = 6;
key.shadow.camera.top = 6;
key.shadow.camera.bottom = -6;
scene.add(key);
const fill = new THREE.DirectionalLight(0x88aaff, 0.35);
fill.position.set(-5, 4, -4);
scene.add(fill);

// Board group (tiles + base). Tinted toward the target colour as a hint.
const boardGroup = new THREE.Group();
scene.add(boardGroup);

const baseGeo = new THREE.BoxGeometry(BOARD * S + 0.5, 0.4, BOARD * S + 0.5);
const baseMat = new THREE.MeshStandardMaterial({ color: 0x161a26, roughness: 0.9 });
const base = new THREE.Mesh(baseGeo, baseMat);
base.position.y = -0.2 - 0.001;
base.receiveShadow = true;
boardGroup.add(base);

const tileGeo = new THREE.BoxGeometry(S * 0.94, 0.12, S * 0.94);
const tileMats = [];
for (let r = 0; r < BOARD; r++) {
  for (let c = 0; c < BOARD; c++) {
    const mat = new THREE.MeshStandardMaterial({
      color: (r + c) % 2 ? 0x222838 : 0x2a3145,
      roughness: 0.85,
    });
    const tile = new THREE.Mesh(tileGeo, mat);
    tile.position.set(cellX(c), -0.06, cellZ(r));
    tile.receiveShadow = true;
    boardGroup.add(tile);
    tileMats.push(mat);
  }
}

// Floating cursor that marks the selected cube.
const cursor = new THREE.Group();
{
  const ringGeo = new THREE.TorusGeometry(0.34, 0.05, 12, 28);
  const ringMat = new THREE.MeshStandardMaterial({
    color: 0x6ee7ff, emissive: 0x2a6f88, roughness: 0.3, metalness: 0.2,
  });
  const ring = new THREE.Mesh(ringGeo, ringMat);
  ring.rotation.x = Math.PI / 2;
  cursor.add(ring);
}
scene.add(cursor);

/* --- Cube objects ----------------------------------------------------------- */

const cubeGeo = new THREE.BoxGeometry(S, S, S);

class Cube {
  constructor(row, col) {
    this.mesh = new THREE.Mesh(cubeGeo, FACE_MATERIALS);
    this.mesh.castShadow = true;
    this.mesh.receiveShadow = true;
    scene.add(this.mesh);
    this.setCell(row, col);
    this.mesh.quaternion.identity(); // solved
    this.syncMesh();
  }
  setCell(row, col) {
    this.row = row;
    this.col = col;
  }
  syncMesh() {
    this.mesh.position.set(cellX(this.col), HALF, cellZ(this.row));
  }
  get topColor() {
    return topColor(this.mesh.quaternion);
  }
  dispose() {
    scene.remove(this.mesh);
  }
}

/* --- Game state ------------------------------------------------------------- */

const game = {
  level: 1,
  bonus: 0, // carried-over moves earned by clearing levels
  cubes: [],
  selected: null, // index into cubes
  moves: 0,
  targetColor: SOLVED_COLOR,
  state: "menu", // menu | playing | won | lost
  anim: null, // active roll animation
};

const el = {
  level: document.getElementById("level"),
  moves: document.getElementById("moves"),
  cubes: document.getElementById("cubes"),
  overlay: document.getElementById("overlay"),
  title: document.getElementById("overlay-title"),
  body: document.getElementById("overlay-body"),
  btn: document.getElementById("overlay-btn"),
};

function cubeAt(row, col) {
  return game.cubes.find((c) => c.row === row && c.col === col) || null;
}

function occupied(row, col) {
  return game.cubes.some((c) => c.row === row && c.col === col);
}

/* --- Level generation ------------------------------------------------------
 * Start from a solved board (all cubes identity-oriented => white up) placed in
 * random empty cells, then apply N random reverse-rolls. Because every scramble
 * step is a legal roll, reversing the sequence solves the board => guaranteed
 * solvable. The scramble count gives a natural par for the move budget.
 * ------------------------------------------------------------------------- */

function levelParams(level) {
  const numCubes = Math.min(25, 2 + level);
  const scramble = 3 + Math.floor(level * 1.6);
  return { numCubes, scramble };
}

function scrambleRoll(cube) {
  // Pick a random direction whose target cell is on-board and empty, then roll.
  const keys = Object.keys(DIRS).sort(() => Math.random() - 0.5);
  for (const k of keys) {
    const d = DIRS[k];
    const nr = cube.row + d.dr, nc = cube.col + d.dc;
    if (!inBounds(nr, nc) || occupied(nr, nc)) continue;
    applyRollLogic(cube, d, nr, nc);
    return true;
  }
  return false;
}

// Apply a roll to logical + mesh state instantly (no animation).
function applyRollLogic(cube, dir, nr, nc) {
  const q = new THREE.Quaternion().setFromAxisAngle(dir.axis, dir.angle);
  cube.mesh.quaternion.premultiply(q);
  cube.setCell(nr, nc);
  cube.syncMesh();
}

function buildLevel(level) {
  // clear old cubes
  for (const c of game.cubes) c.dispose();
  game.cubes = [];

  const { numCubes, scramble } = levelParams(level);

  // place cubes in distinct random cells, solved orientation
  const cells = [];
  for (let r = 0; r < BOARD; r++) for (let c = 0; c < BOARD; c++) cells.push([r, c]);
  cells.sort(() => Math.random() - 0.5);
  for (let i = 0; i < numCubes; i++) {
    const [r, c] = cells[i];
    game.cubes.push(new Cube(r, c));
  }

  // scramble with random reverse-rolls
  let applied = 0, guard = 0;
  while (applied < scramble && guard < scramble * 20) {
    guard++;
    const cube = game.cubes[randInt(game.cubes.length)];
    if (scrambleRoll(cube)) applied++;
  }

  game.targetColor = SOLVED_COLOR;
  game.moves = scramble + 3 + game.bonus; // par + slack + carried bonus
  game.selected = 0;

  // If by luck the scramble produced an already-uniform board, nudge once more.
  if (isUniform()) scrambleRoll(game.cubes[randInt(game.cubes.length)]);

  tintBoard(game.targetColor);
  updateCursor(true);
  updateHud();
}

/* --- Win / lose ------------------------------------------------------------- */

function isUniform() {
  if (game.cubes.length === 0) return false;
  const t = game.cubes[0].topColor;
  return game.cubes.every((c) => c.topColor === t);
}

function tintBoard(colorId) {
  const c = new THREE.Color(COLORS[colorId].hex);
  for (const m of tileMats) {
    m.emissive = c;
    m.emissiveIntensity = 0.12;
  }
  baseMat.emissive = c;
  baseMat.emissiveIntensity = 0.05;
}

/* --- Input / rolling -------------------------------------------------------- */

function selectCube(idx) {
  game.selected = idx;
  updateCursor(true);
}

function tryMove(key) {
  if (game.state !== "playing" || game.anim) return;
  const dir = DIRS[key];
  if (!dir) return;
  const cube = game.cubes[game.selected];
  const nr = cube.row + dir.dr, nc = cube.col + dir.dc;
  if (!inBounds(nr, nc)) return; // edge: nothing happens

  const other = cubeAt(nr, nc);
  if (other) {
    // re-select neighbour — free, no move spent
    selectCube(game.cubes.indexOf(other));
    return;
  }

  if (game.moves <= 0) return;
  startRoll(cube, dir, nr, nc);
}

function startRoll(cube, dir, nr, nc) {
  const center = cube.mesh.position.clone();
  const pivot = center.clone().add(dir.edgeOffset);
  game.anim = {
    cube, dir, nr, nc, pivot,
    startPos: center.clone().sub(pivot), // position relative to pivot
    startQuat: cube.mesh.quaternion.clone(),
    t: 0,
  };
  game.moves -= 1;
  updateHud();
}

function stepRoll(dt) {
  const a = game.anim;
  a.t = Math.min(1, a.t + dt / ROLL_MS);
  // ease-in-out for a satisfying tip
  const e = a.t < 0.5 ? 2 * a.t * a.t : 1 - Math.pow(-2 * a.t + 2, 2) / 2;
  const angle = a.dir.angle * e;
  const q = new THREE.Quaternion().setFromAxisAngle(a.dir.axis, angle);
  a.cube.mesh.position.copy(a.startPos).applyQuaternion(q).add(a.pivot);
  a.cube.mesh.quaternion.copy(a.startQuat).premultiply(q);

  if (a.t >= 1) {
    // snap to final logical state
    const final = new THREE.Quaternion().setFromAxisAngle(a.dir.axis, a.dir.angle);
    a.cube.mesh.quaternion.copy(a.startQuat).premultiply(final);
    a.cube.setCell(a.nr, a.nc);
    a.cube.syncMesh();
    game.anim = null;
    updateCursor(false);
    afterMove();
  } else {
    updateCursor(false);
  }
}

function afterMove() {
  if (isUniform()) {
    game.state = "won";
    game.bonus += 1; // clearing a level grants +1 carried move
    showOverlay(
      "Solved!",
      `Level ${game.level} cleared. <b>+1</b> bonus move banked (carried: ${game.bonus}).`,
      "Next level"
    );
  } else if (game.moves <= 0) {
    game.state = "lost";
    showOverlay("Out of moves", "Not quite. Give it another go.", "Retry");
  }
}

/* --- Presentation: cursor + HUD -------------------------------------------- */

function updateCursor(snap) {
  const cube = game.cubes[game.selected];
  if (!cube) return;
  const tx = cube.mesh.position.x;
  const tz = cube.mesh.position.z;
  if (snap) {
    cursor.position.set(tx, S + 0.45, tz);
  } else {
    cursor.position.x += (tx - cursor.position.x) * 0.4;
    cursor.position.z += (tz - cursor.position.z) * 0.4;
    cursor.position.y = S + 0.45;
  }
}

function updateHud() {
  el.level.textContent = game.level;
  el.moves.textContent = Math.max(0, game.moves);
  el.cubes.textContent = game.cubes.length;
}

function showOverlay(title, body, btn) {
  el.title.textContent = title;
  el.body.innerHTML = body;
  el.btn.textContent = btn;
  el.overlay.classList.remove("hidden");
}

function hideOverlay() {
  el.overlay.classList.add("hidden");
}

/* --- Flow control ----------------------------------------------------------- */

function startGame() {
  game.level = 1;
  game.bonus = 0;
  hideOverlay();
  buildLevel(game.level);
  game.state = "playing";
}

function nextLevel() {
  game.level += 1;
  hideOverlay();
  buildLevel(game.level);
  game.state = "playing";
}

function retryLevel() {
  hideOverlay();
  buildLevel(game.level); // fresh scramble of the same level index
  game.state = "playing";
}

function overlayAction() {
  if (game.state === "menu") startGame();
  else if (game.state === "won") nextLevel();
  else retryLevel(); // lost
}

el.btn.addEventListener("click", overlayAction);

window.addEventListener("keydown", (e) => {
  if (DIRS[e.key]) {
    e.preventDefault();
    if (game.state === "playing") tryMove(e.key);
    return;
  }
  if (e.key === "Enter" || e.key === " ") {
    if (!el.overlay.classList.contains("hidden")) {
      e.preventDefault();
      overlayAction();
    }
  } else if (e.key === "r" || e.key === "R") {
    if (game.state === "playing" || game.state === "lost") retryLevel();
  }
});

/* --- Render loop ------------------------------------------------------------ */

function resize() {
  const w = window.innerWidth, h = window.innerHeight;
  renderer.setSize(w, h, false);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
}
window.addEventListener("resize", resize);
resize();

let last = performance.now();
function loop(now) {
  const dt = Math.min(now - last, 50);
  last = now;

  if (game.anim) stepRoll(dt);

  // animate cursor: bob + spin
  cursor.rotation.z += dt * 0.003;
  cursor.children[0].position.y = Math.sin(now * 0.004) * 0.06;

  renderer.render(scene, camera);
  requestAnimationFrame(loop);
}

// Boot
showOverlay(
  "kCube",
  "Roll the cubes so they all show the <b>same colour</b> on top — before you run out of moves. Use the arrow keys.",
  "Play"
);
requestAnimationFrame(loop);
